[project]
name = "maracutala-collect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "fastparquet>=2026.3.0",
    "ipykernel>=7.2.0",
    "pandas>=3.0.2",
    "psycopg2>=2.9.12",
    "pyarrow>=24.0.0",
    "pydantic>=2.13.3",
    "pydantic-settings>=2.14.0",
    "requests>=2.33.1",
    "sqlalchemy>=2.0.49",
    "tqdm>=4.67.3",
    "urllib3>=2.6.3",
]
